Site/urls.py
from django.urls import path
from . import views
from .views import *

from django.contrib.auth import views as auth_views



app_name ='Site'
urlpatterns=[
    path('', PostIndexView.as_view(), name='ex2'),
    path('add/', PostAddView.as_view(), name='add'),
    path('g/<str:genre>', PostGenreView.as_view(), name='genre'),
    path('<int:pk>/edit', PostUpdateView.as_view(), name='post_edit'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path("<int:pk>/", views.Post_detail, name="post_detail"),
    path("<category>/", views.Post_category, name="post_category"),
    

]

myown/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name ='Site'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Site.urls')),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Site/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class  Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    date_created =models.DateTimeField(auto_now_add=True, null=True)


class Post(models.Model):
    
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now=True)
    last_modified = models. DateTimeField(auto_now=True)
    Categories = models.ManyToManyField('Category', related_name='posts')
    image = models.ImageField(default="profile1.png", null=True, blank=True)
    def __str__(self):
        return self.title
    

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url 
    
    

class Comment(models.Model):
    
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models. ForeignKey('post', on_delete=models.CASCADE)
            

Site/forms.py
from django import forms
from . models import *
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User



class postForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={"class":"forms", "rows":3, "placeholder": "descriptions"}))

    class Meta:
        model = Post
        fields = ('title', 'body', 'Categories', 'image')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', "placeholder": "enter title"}),
            
           
        }

class CommentForm(forms.Form):
    
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
        )
    

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User 
        fields = ('username', 'email', 'password1', 'password2',)

        widgets = {
            'email': forms.EmailInput(attrs={'class':'input', 'placeholder': 'Email Address'})
    
    }    

Site/views.py
from django.shortcuts import render
from .models import *
from .forms import *


from django.views.generic.list import ListView

from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

from django.db.models import F
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator






# Create your views here.

class PostDeleteView(DeleteView):

    model = Post
    template_name = 'app/delete.html'
    context_object_name = 'post'
    success_url = '/'

    



class PostUpdateView( UpdateView):
    

    model = Post
    template_name = 'app/add.html'
    form_class = postForm
    success_url = '/'

"""
class AddBookView(FormView):
    template_name = 'add.html'
    form_class = AddForm
    success_url = '/books/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
"""       
class PostAddView(CreateView):
    model = Post
    template_name = 'app/add.html'
    form_class = postForm
    success_url = '/'



"""
class IndexView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Books.objects.all()
        return context
"""



class PostIndexView( ListView):
    model = Post
    template_name = "app/home.html"
    context_object_name = 'posts'
    paginate_by = 2

    #def get_queryset(self):
        #return Books.objects.all()[:3]


class PostGenreView(ListView):
    model = Post
    template_name = 'app/home.html'
    context_object_name = 'posts'
    paginate_by = 1

    def get_queryset(self, *args, **kwargs):
        return Post.objects.filter(genre__icontains=self.kwargs.get('title'))
    

def Post_category(request, category):
    posts = Post.objects.filter(
        Categories__name__contains=category
    ).order_by(
        'created_on'
    )    
    context = {
        "Category": category,
        "posts": posts
    }
    return render(request, "app/post_category.html", context)


def Post_detail(request, pk):
    post = Post.objects.get(pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        "comments": comments,
        "form": form,
    }
    return render(request, "app/post_detail.html", context)

Site/templates/app/add.html
{% extends "app/base.html" %}
{% block content %}

    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, textarea, label { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      color: #666;
      line-height: 22px;
      }
      h1 {
      position: absolute;
      margin: 0;
      font-size: 40px;
      color: #fff;
      z-index: 2;
      line-height: 83px;
      }
      .testbox {
      display: flex;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 20px;
      }
      form {
      width: 100%;
      padding: 20px;
      border-radius: 6px;
      background: #fff;
      box-shadow: 0 0 8px  #cc7a00; 
      }
      .banner {
      position: relative;
      height: 300px;
      background-image: url("/static/images/banner/banner1.jpg");  
      background-size: cover;
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
      }
      .banner::after {
      content: "";
      background-color: rgba(0, 0, 0, 0.2); 
      position: absolute;
      width: 100%;
      height: 100%;
      }
      input, select, textarea {
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 3px;
      }
      input {
      width: calc(100% - 10px);
      padding: 5px;
      }
      input[type="date"] {
      padding: 4px 5px;
      }
      textarea {
      width: calc(100% - 12px);
      padding: 5px;
      }
      .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
      color: #cc7a00;
      }
      .item input:hover, .item select:hover, .item textarea:hover {
      border: 1px solid transparent;
      box-shadow: 0 0 3px 0 #cc7a00;
      color: #cc7a00;
      }
      .item {
      position: relative;
      margin: 10px 0;
      }
      .item span {
      color: red;
      }
      input[type="date"]::-webkit-inner-spin-button {
      display: none;
      }
      .item i, input[type="date"]::-webkit-calendar-picker-indicator {
      position: absolute;
      font-size: 20px;
      color: #cc7a00;
      }
      .item i {
      right: 1%;
      top: 30px;
      z-index: 1;
      }
      [type="date"]::-webkit-calendar-picker-indicator {
      right: 1%;
      z-index: 2;
      opacity: 0;
      cursor: pointer;
      }
      input[type=radio], input[type=checkbox]  {
      display: none;
      }
      label.radio {
      position: relative;
      display: inline-block;
      margin: 5px 20px 15px 0;
      cursor: pointer;
      }
      .question span {
      margin-left: 30px;
      }
      .question-answer label {
      display: block;
      }
      label.radio:before {
      content: "";
      position: absolute;
      left: 0;
      width: 17px;
      height: 17px;
      border-radius: 50%;
      border: 2px solid #ccc;
      }
      input[type=radio]:checked + label:before, label.radio:hover:before {
      border: 2px solid #cc7a00;
      }
      label.radio:after {
      content: "";
      position: absolute;
      top: 6px;
      left: 5px;
      width: 8px;
      height: 4px;
      border: 3px solid #cc7a00;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      button {
      width: 150px;
      padding: 10px;
      border: none;
      border-radius: 5px; 
      background: #cc7a00;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }
      button:hover {
      background: #ff9800;
      }
      @media (min-width: 568px) {
      .name-item, .city-item {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .name-item input, .name-item div {
      width: calc(50% - 20px);
      }
      .name-item div input {
      width:97%;}
      .name-item div label {
      display:block;
      padding-bottom:5px;
      }
      }
    </style>
    
    
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <button><a href="{% url 'Site:ex2'  %}"><i class="im im-angel-left"></i>back</a></button>
      <div class="banner">
        <h1>NEW PROJECT</h1>
      </div>
      <br>
      

      <form class="form" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="form__field">
          <label for="formInput#text">{{field.label}}</label>
          {{field}}
        </div>
        {% endfor %}
        <div class="btn-block">
          <button type="submit" value="SUBMIT">SUBMIT</button>
        </div>
      </form>

    </div>
  </div>
</main>

</html> 

  
{% endblock %}

Site/templates/app/delete.html
{% extends 'app/base.html' %}

{% block content %}


<p>Are you sure you want to delete "{{book}}"?</p>
<form method="post">
    {% csrf_token %}
    <a href="{% url 'Site:post_detail' post.pk %}">cancel</a>
    <input type="submit">
</form>

{% endblock %}

Site/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="slideshow-container">
  
    <div class="mySlides fade">
      <div class="numbertext">1 / 3</div>
      <img src="{% static 'images/slider-main/bg1.jpg' %}" style="max-height: 1000px; max-width: 2000px;">
      <div class="text">project one</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">2 / 3</div>
      <img src="{% static 'images/slider-main/bg2.jpg' %}" style="max-height: 1000px; max-width: 2000px;">
      <div class="text">Project two</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">3 / 3</div>
      <img src="{% static 'images/slider-main/bg3.jpg' %}" style="max-height: 1000px; max-width: 2000px;">
      <div class="text">project Three</div>
    </div>
    
    </div>
    <br>
    
    <div style="text-align:center">
      <span class="dot"></span> 
      <span class="dot"></span> 
      <span class="dot"></span> 
    </div>
    
    <script>
    let slideIndex = 0;
    showSlides();
    
    function showSlides() {
      let i;
      let slides = document.getElementsByClassName("mySlides");
      let dots = document.getElementsByClassName("dot");
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";  
      }
      slideIndex++;
      if (slideIndex > slides.length) {slideIndex = 1}    
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";  
      dots[slideIndex-1].className += " active";
      setTimeout(showSlides, 2000); // Change image every 0 second
    }
    </script>
    <hr>
    <section class="call-to-action-box no-padding">
        <div class="container">
          <div class="action-style-box">
              <div class="row align-items-center">
                <div class="col-md-8 text-center text-md-left">
                    <div class="call-to-action-text">
                      <h3 class="action-title">We understand your needs on projects</h3>
                    </div>
                </div><!-- Col end -->
                <div class="col-md-4 text-center text-md-right mt-3 mt-md-0">
                    <div class="call-to-action-btn">
                      
                    </div>
                </div><!-- col end -->
              </div><!-- row end -->
          </div><!-- Action style box -->
        </div><!-- Container end -->
      </section><!-- Action end -->
    
    </body>
    </html> 

    {% for post in posts %}
          <div class="row shuffle-wrapper">
            <div class="col-1 shuffle-sizer"></div>
  
            <div class="col-lg-4 col-md-6 shuffle-item" data-groups="[&quot;government&quot;,&quot;healthcare&quot;]">
              <div class="project-img-container">
                <a class="gallery-popup" href="{{post.imageURL}}">
                  <img class="img-fluid" src="{{post.imageURL}}" alt="project-image" style="height: 500px; width: 500px;">
                  <span class="gallery-icon"><i class="fa fa-plus"></i></span>
                
                <div class="project-item-info">
                 <div class="project-item-info-content">
                    <h3 class="project-item-title">
                      <a href="{% url 'Site:post_detail' post.pk %}">{{post.title|truncatechars:50}} {% if project.topRated %}<strong>TOP RATED</strong> {% endif %}</a>
                    </h3>
                    <div class="project-cat">
                        {% for category in post.Categories.all %}
                      <span class="tag tag--pill tag--main">
                        <a href="{% url 'Site:post_category' category.name %}">
                            {{ category.name }}
                        </a>&nbsp;
                      </span>
                      <span class="gallery-icon"><i class="fa fa-plus"></i></span>
                      {% endfor %}
                    </div>
                </div>
                </div>
              </div>   
              </div>
            </div>
          </div>
          <div class="project-item-info">
            <div class="project-item-info-content">
               <h3 class="project-item-title">
                 <a href="{% url 'Site:post_detail' post.pk %}">{{post.title|truncatechars:50}} {% if project.topRated %}<strong>TOP RATED</strong> {% endif %}</a>
               </h3>
               <div class="project-cat">
                   {% for category in post.Categories.all %}
                 <span class="tag tag--pill tag--main">
                   <a href="{% url 'Site:post_category' category.name %}">
                       {{ category.name }}
                   </a>&nbsp;
                 </span>
                 <span class="gallery-icon"><i class="fa fa-plus"></i></span>
                 {% endfor %}
               </div>
           </div>
          <small class="text-muted">{{post.created_on}}</small>
          <hr>
          <small class="text-muted">{{post.body}}</small>
        </a>

        </div>
            <table>
                 <td>
                <div class="call-to-action-btn">
                  <a class="btn btn-primary" href="{% url 'Site:post_edit' post.pk %}">Edit</a>
                </div>
                 </td>
                 <td>
                    <div class="call-to-action-btn">
                      <a class="btn btn-primary" href="{% url 'Site:post_delete' post.pk %}">Delete</a>
                    </div>
                 </td>
              </table>
            </div><!-- shuffle item 1 end -->
              {% endfor %}
              <hr>
  
  
        <div class="col-12">
          <div class="general-btn text-center">
            <a class="btn btn-primary" href="{% url 'Site:ex2'  %}">Projects Home</a>
          </div>
        </div>
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
        
      </div><!-- Content row end -->
  
    </div><!-- Conatiner end -->
  </section><!-- Main container end -->
 

{% endblock %}

Site/templates/app/navbar.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
================================================== -->
  <meta charset="utf-8">
  <title>Constra - Construction Html5 Template</title>

  <!-- Mobile Specific Metas
================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Construction Html5 Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name=author content="Themefisher">
  <meta name=generator content="Themefisher Constra HTML Template v1.0">

  <!-- Favicon
================================================== -->


  <!-- CSS
================================================== -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- FontAwesome -->
  
  <link rel="stylesheet" href="{% static 'plugins/animate-css/animate.css' %}">
 
  
  <link rel="stylesheet" href="{% static 'plugins/colorbox/colorbox.css' %}">
  <!-- Template styles-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  <div class="body-inner">

    <div id="top-bar" class="top-bar">
        <div class="container">
          <div class="row">
              <div class="col-lg-8 col-md-8">
                <ul class="top-info text-center text-md-left">
                    <li><i class="fas fa-map-marker-alt"></i> <p class="info-text">DE-JII</p>
                    </li>
                </ul>
              </div>
              <!--/ Top info end -->
  
              <div class="col-lg-4 col-md-4 top-social text-center text-md-right">
                <ul class="list-unstyled">
                    <li>
                      <a title="Facebook" href="https://facebbok.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-facebook-f"></i></span>
                      </a>
                      <a title="Twitter" href="https://twitter.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-twitter"></i></span>
                      </a>
                      <a title="Instagram" href="https://instagram.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-instagram"></i></span>
                      </a>
                      <a title="Linkdin" href="https://github.com/themefisher.com">
                          <span class="social-icon"><i class="fab fa-github"></i></span>
                      </a>
                    </li>
                </ul>
              </div>
              <!--/ Top social end -->
          </div>
          <!--/ Content row end -->
        </div>
        <!--/ Container end -->
    </div>
    <!--/ Topbar end -->
<!-- Header start -->
<header id="header" class="header-one">
  <div class="bg-white">
    <div class="container">
      <div class="logo-area">
          <div class="row align-items-center">
            <div class="Logo">
                
                <img style="max-width: 500;" src="{% static 'images/Logo.jpg' %}">
                </a>
            </div><!-- logo end -->
  
            <div class="col-lg-9 header-right">
                <ul class="top-info-box">
                
                </ul><!-- Ul end -->
            </div><!-- header right end -->
          </div><!-- logo area end -->
            
      </div><!-- Row end -->
    </div><!-- Container end -->
  </div>
  <div class="site-navigation">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <nav class="navbar navbar-expand-lg navbar-dark p-0">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div id="navbar-collapse" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav mr-auto">
                    
              
                      
                      <li class="nav-item"><a class="nav-link" href="{% url 'Site:ex2' %}">PROJECTS</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url 'Site:add' %}">ADD PROJECT</a></li>
                      <li class="nav-item active">
                        <a class="nav-link">Hello,{{user.name}}</a>
                      </li>
                    </ul>
                   
                </div>
              </nav>
          </div>
          <!--/ Col end -->
        </div>
        <!--/ Row end -->

        <div class="nav-search">
          <span id="search"><i class="fa fa-search"></i></span>
        </div><!-- Search end -->

        <div class="search-block" style="display: none;">
          <label for="search-field" class="w-100 mb-0">
            <input type="text" class="form-control" id="search-field" placeholder="Type what you want and enter">
          </label>
          <span class="search-close">&times;</span>
        </div><!-- Site search end -->
    </div>
    <!--/ Container end -->

  </div>
  <!--/ Navigation end -->
</header>                     

Site/templates/app/post_category.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="slideshow-container">
  
    <div class="mySlides fade">
      <div class="numbertext">1 / 3</div>
      <img src="{% static 'images/slider-main/bg1.jpg' %}" style="max-height: 1000px; max-width: 2000px;">
      <div class="text">project one</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">2 / 3</div>
      <img src="{% static 'images/slider-main/bg2.jpg' %}" style="max-height: 1000px; max-width: 2000px;">
      <div class="text">Project two</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">3 / 3</div>
      <img src="{% static 'images/slider-main/bg3.jpg' %}" style="max-height: 1000px; max-width: 2000px;">
      <div class="text">project Three</div>
    </div>
    
    </div>
    <br>
    
    <div style="text-align:center">
      <span class="dot"></span> 
      <span class="dot"></span> 
      <span class="dot"></span> 
    </div>
    
    <script>
    let slideIndex = 0;
    showSlides();
    
    function showSlides() {
      let i;
      let slides = document.getElementsByClassName("mySlides");
      let dots = document.getElementsByClassName("dot");
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";  
      }
      slideIndex++;
      if (slideIndex > slides.length) {slideIndex = 1}    
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";  
      dots[slideIndex-1].className += " active";
      setTimeout(showSlides, 2000); // Change image every 0 second
    }
    </script>
    <hr>
    <section class="call-to-action-box no-padding">
        <div class="container">
          <div class="action-style-box">
              <div class="row align-items-center">
                <div class="col-md-8 text-center text-md-left">
                    <div class="call-to-action-text">
                      <h3 class="action-title">We understand your needs on projects</h3>
                    </div>
                </div><!-- Col end -->
                <div class="col-md-4 text-center text-md-right mt-3 mt-md-0">
                    <div class="call-to-action-btn">
                      <a class="btn btn-dark" href="#">login/sign up</a>
                    </div>
                </div><!-- col end -->
              </div><!-- row end -->
          </div><!-- Action style box -->
        </div><!-- Container end -->
      </section><!-- Action end -->
    
    </body>
    </html> 

    {% for post in posts %}
          <div class="row shuffle-wrapper">
            <div class="col-1 shuffle-sizer"></div>
  
            <div class="col-lg-4 col-md-6 shuffle-item" data-groups="[&quot;government&quot;,&quot;healthcare&quot;]">
              <div class="project-img-container">
                <a class="gallery-popup" href="{{post.imageURL}}">
                  <img class="img-fluid" src="{{post.imageURL}}" alt="project-image" style="height: 500px; width: 500px;">
                  <span class="gallery-icon"><i class="fa fa-plus"></i></span>
                </a>
                <div class="project-item-info">
                  <div class="project-item-info-content">
                    <h3 class="project-item-title">
                      <a href="{% url 'Site:post_detail' post.pk %}">{{post.title|truncatechars:50}} {% if project.topRated %}<strong>TOP RATED</strong> {% endif %}</a>
                    </h3>
                    <div class="project-cat">
                        {% for category in post.Categories.all %}
                      <span class="tag tag--pill tag--main">
                        <a href="{% url 'Site:post_category' category.name %}">
                            {{ category.name }}
                        </a>&nbsp;
                      </span>
                      <span class="gallery-icon"><i class="fa fa-plus"></i></span>
                      {% endfor %}
                  </div>
                    <small class="text-muted">{{post.body}}</small>
                    <small class="text-muted">{{post.created_on}}</small>
        
                  </div>
                </div>
              </div>
            </div>
            <table>
                 <td>
                <div class="call-to-action-btn">
                  <a class="btn btn-primary" href="{% url 'Site:post_edit' post.pk %}">Edit</a>
                </div>
                 </td>
                 <td>
                    <div class="call-to-action-btn">
                      <a class="btn btn-primary" href="{% url 'Site:post_delete' post.pk %}">Delete</a>
                    </div>
                 </td>
              </table>
            </div><!-- shuffle item 1 end -->
              {% endfor %}
              <hr>
  
  
        <div class="col-12">
          <div class="general-btn text-center">
            <a class="btn btn-primary" href="{% url 'Site:ex2'  %}">Projects Home</a>
          </div>
        </div>
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
        
      </div><!-- Content row end -->
  
    </div><!-- Conatiner end -->
  </section><!-- Main container end -->
 

{% endblock %}

Site/templates/app/post_detail.html
{% extends 'app/base.html' %}
{% block content %}

  <section id="main-container" class="main-container">
    <div class="container">
  
      <div class="row">
        <div class="col-lg-8">
          <div id="page-slider" class="page-slider small-bg">
            <div class="item">
                <img style="max-height: 500px; max-width: 800px;" src="{{post.imageURL}}" />
                <h1>{{ post.title }}</h1>
            </div>
          </div><!-- Page slider end -->
        </div><!-- Slider col end -->
  
        <div class="col-lg-4 mt-5 mt-lg-0">
            <h2>{{project.title}}</h2>
            <div class="btn btn-primary">
                Categories:&nbsp;
                    {% for category in post.Categories.all %}
                    <a href="{% url 'Site:post_category' category.name %}">
                        {{ category.name }}
                    </a>&nbsp;
                
                <span class="gallery-icon"><i class="fa fa-plus"></i></span>
                {% endfor %}
            </div>
            {% if project.source_code %}
            <p>
                <div class="btn btn-dark">
                    <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code</a>
                </div>
            </p>
            {% endif %}
        

        <hr>
        <h3 class="singleProject__subtitle">About the Project</h3>


        <p>{{ post.body | linebreaks }}</p>

        <hr>

        <h3>Leave a comment:</h3>
        <form action="/{{ post.pk }}/" method="post">
            {% csrf_token %}
            
            <div class="form-group">
                {{ form.body }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <h3>Comments:</h3>
        {% for comment in comments %}
        <p>
            on{{ comment.created_on.date }}&nbsp;
            <b>{{ comment.profile.name }}</b> wrote:
        </p>
        <p>{{ comment.body }}</p>
        <hr>
        {% endfor %}
  
          
        </div><!-- Content col end -->
  
      </div><!-- Row end -->
  
    </div><!-- Conatiner end -->
  </section><!-- Main container end -->
  
{% endblock %}
Categories:&nbsp;
{% for category in post.Categories.all %}
<a href="{% url 'Site:post_category' category.name %}">
    {{ category.name }}
</a>&nbsp;
{% endfor %}
    </div>